### ISSUE TITLE
How to procure hardware?

### ISSUE THREAD

**Issue by mm3509** [riosil/EdgeLEDcontroller#1]
Hello Steven! This is Miguel from Makespace. Thanks for making this public!

Are you selling the hardware: wood, LED and controller?

If not, I would like to procure some. The README says ATtiny85 but the image shows a different one. Could you please include a list of gear to buy to replicate the project?

**Comment by riosil** [comment]
Thanks Miguel, no plans to sell atm but I'll make a few bare v2 PCBs available in MakeSpace (free). I was hoping my demo projects in the 'space would inspire more edge lit display projects

Profiles to make the wood parts are in the laser_cutter folder. For LEDs, search AliExpress for SK6812MINI or WS2812B, choose spacing and size to suit project.

I just generated a BoM (in the KiCAD folder). This project has only ever used the ATtiny85.

**Comment by riosil** [comment]
...ah I see the confusion. The initial commit message stated "ATtiny85 version". At the time, 3 years ago, I was planning an ATSAMD21 Cortex M0 version. Then the pandemic struck. The crazy lead times and pricing put me off Microchip SAMD parts. I'd rather try and squeeze in an RP2040. No plans for this ATM.

**Comment by mm3509** [comment]
Thanks Steven! Regarding the bare PCBs, unfortunately I left Cambridge shortly before the pandemic and haven't come back since.

For the wood parts, I'll probably make 3D model (I have no laser cutter nearby). I'll submit a pull request when I have it.

For LEDs, thanks for the tip, I will do that or maybe dig around for existing ones I bought a few years ago.

Thanks for the Bill of Materials, now I see the details of all items and can source them.

For the PCB, I uploaded the zipped KiCAD file to OSHPark and got this message:

> Upload failed
> Sorry! something went wrong with your upload
> 
> Notes
> Processing information
> Processing EdgeLED2.zip as generic ZIP file.
> Failure (critical)
> We couldn't find a copper layer.
> We couldn't find the board outline.

Which supplier would you recommend as to order this PCB in small quantities (1-5 items)?

This is my first time ordering PCBs, will they come with resistors and capacitors mounted on them or would I need to procure them and solder myself?

My confusion around the ATtiny85 is that when I searched for it, the first few images did not match the picture on the README, and the words on the microchip from the image didn't say ATtiny85. But now that I see the bill of materials, it's all clear, thanks.

Thanks a lot!

**Comment by mm3509** [comment]
Never mind: in the `CAM` directory, I see the README that suggests JLCPCB. I tried it and it works. The Bill of Materials also works and JLCPCB can source most of them and assemble them too. So, for the electronics, it's as simple as that at https://jlcpcb.com/ .

ATtiny85 is currently out of inventory. So I'll try again in a few months. Also, for anyone in the future, the "Pick&Place" CPL file is `EdgeLED2-top-pos.csv`.

**Comment by mm3509** [comment]
Thanks for your help with the PCB; unfortunately JLCPCB didn't have them in stock when I wanted to buy them, and I tested with some LEDs and the edge lighting doesn't seem to work well with my engravings, either because the acrylic is too thin or because the engraving of a photographic bitmap doesn't work well. If and when you put your PCB and construction on the market, please let me know!
